name: push

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_NAME: nikover/devops-for-programmers-project-74

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Копируем код, чтобы к нему был доступ
      - name: Copy app code
        uses: actions/checkout@v4
      # Запускаем тесты
      - name: Run test
        run: make test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Копируем код, чтобы к нему был доступ
      - name: Copy app code
        uses: actions/checkout@v4
      # Получаем доступ к докерхабу
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -f Dockerfile.prod -t ${{ env.APP_IMAGE_NAME }}:latest .
          docker push ${{ env.APP_IMAGE_NAME }}:latest
